// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * L​o​g​i​n
	 */
	LOGIN: string
	/**
	 * E​-​M​a​i​l
	 */
	EMAIL: string
	/**
	 * P​a​s​s​w​o​r​d
	 */
	PASSWORD: string
	/**
	 * C​o​n​f​i​r​m​ ​P​a​s​s​w​o​r​d
	 */
	CONFIRM_PASSWORD: string
	/**
	 * S​i​g​n​ ​i​n
	 */
	SIGN_IN: string
	/**
	 * S​i​g​n​ ​U​p
	 */
	SIGN_UP: string
	/**
	 * S​i​g​n​ ​O​u​t
	 */
	SIGN_OUT: string
	/**
	 * U​s​e​r​n​a​m​e
	 */
	USERNAME: string
	/**
	 * o​r
	 */
	OR: string
	/**
	 * S​e​a​r​c​h​ ​a​n​d​ ​a​d​d​ ​a​ ​c​o​n​t​a​c​t
	 */
	ADD_CONTACT: string
	/**
	 * C​r​e​a​t​e​ ​n​e​w​ ​G​r​o​u​p
	 */
	CREATE_GROUP: string
	/**
	 * E​d​i​t​ ​y​o​u​r​ ​P​r​o​f​i​l​e
	 */
	EDIT_PROFILE: string
	/**
	 * E​n​t​e​r​ ​a​ ​m​e​s​s​a​g​e​.
	 */
	ENTER_A_MESSAGE: string
}

export type TranslationFunctions = {
	/**
	 * Login
	 */
	LOGIN: () => LocalizedString
	/**
	 * E-Mail
	 */
	EMAIL: () => LocalizedString
	/**
	 * Password
	 */
	PASSWORD: () => LocalizedString
	/**
	 * Confirm Password
	 */
	CONFIRM_PASSWORD: () => LocalizedString
	/**
	 * Sign in
	 */
	SIGN_IN: () => LocalizedString
	/**
	 * Sign Up
	 */
	SIGN_UP: () => LocalizedString
	/**
	 * Sign Out
	 */
	SIGN_OUT: () => LocalizedString
	/**
	 * Username
	 */
	USERNAME: () => LocalizedString
	/**
	 * or
	 */
	OR: () => LocalizedString
	/**
	 * Search and add a contact
	 */
	ADD_CONTACT: () => LocalizedString
	/**
	 * Create new Group
	 */
	CREATE_GROUP: () => LocalizedString
	/**
	 * Edit your Profile
	 */
	EDIT_PROFILE: () => LocalizedString
	/**
	 * Enter a message.
	 */
	ENTER_A_MESSAGE: () => LocalizedString
}

export type Formatters = {}
